services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./symfony:/var/www/html
      - ./docker/php-local.ini:/usr/local/etc/php/conf.d/php-local.ini
    ports:
      - "8000:80"
    environment:
      PHP_IDE_CONFIG: "serverName=dev-docker"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - .db_data:/var/lib/mysql

  webserver:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./symfony:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: http --region=eu webserver:80
    env_file:
      - .env.ngrok
    ports:
      - "4040:4040"   # panel www ngrok
    depends_on:
      - webserver




